public class ExcessivePublicCount {
    public String value;
    public Bar something;
    public Variable var;
    public String value1;
    public String value2;
    public String value3;
    public String value4;
    public String value5;
    public String value6;
    public String value7;
    public String value8;
    public String value9;
    public String value10;
    public String value11;
    public String value12;
    public String value13;
    public String value14;
    public String value15;
    public String value16;
    public String value17;
    public String value18;
    public String value19;
    public String value20;
    // [... more more public attributes ...]

    public void doWork() {}
    public void doMoreWork() {}
    public void doWorkAgain() {}
    // [... more more public methods ...]
}
